# Generated by Django 6.0.5 on 2026-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название лабораторной')),
                ('task', models.TextField(verbose_name='Задание')),
                ('code_example', models.TextField(blank=True, verbose_name='Пример кода')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название лекции')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='Раздел')),
                ('content', models.TextField(verbose_name='Текст лекции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Видео'), ('ppt', 'Презентация'), ('other', 'Другое')], default='pdf', max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Файл')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер файла')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название презентации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='presentations/', verbose_name='Файл презентации')),
                ('slides_count', models.PositiveIntegerField(default=0, verbose_name='Количество слайдов')),
            ],
        ),
    ]
