# Generated by Django 6.0.5 on 2026-05-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('option_a', models.CharField(max_length=200, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Вариант D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Правильный ответ')),
            ],
        ),
    ]
