# Generated by Django 6.0.5 on 2026-05-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='laboratories/', verbose_name='Файл лабораторной'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/', verbose_name='Файл лекции'),
        ),
    ]
