# Generated by Django 6.0.5 on 2026-06-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_googletestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='YouTube ссылка'),
        ),
    ]
