# Generated by Django 6.0.1 on 2026-05-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_laboratory_file_lecture_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('form_url', models.URLField(verbose_name='Ссылка Google Forms')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный тест')),
            ],
        ),
    ]
