# Generated by Django 6.0.5 on 2026-06-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_material_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Видео'), ('ppt', 'Презентация'), ('other', 'Другое'), ('youtube', 'YouTube')], default='pdf', max_length=20, verbose_name='Тип файла'),
        ),
    ]
